/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogUsingDisposableEmailForNewsletterSignupRouteImport } from './routes/blog.using-disposable-email-for-newsletter-signup'
import { Route as BlogTemporaryEmailVsPermanentEmailDifferencesRouteImport } from './routes/blog.temporary-email-vs-permanent-email-differences'
import { Route as BlogTemporaryEmailSoftwareTrialsRouteImport } from './routes/blog.temporary-email-software-trials'
import { Route as BlogTemporaryEmailSaasSignupGuideRouteImport } from './routes/blog.temporary-email-saas-signup-guide'
import { Route as BlogTemporaryEmailPrivacyProtectionGuideRouteImport } from './routes/blog.temporary-email-privacy-protection-guide'
import { Route as BlogTemporaryEmailOnlinePrivacyGuideRouteImport } from './routes/blog.temporary-email-online-privacy-guide'
import { Route as BlogTemporaryEmailMembershipSitesGuideRouteImport } from './routes/blog.temporary-email-membership-sites-guide'
import { Route as BlogTemporaryEmailLeadGenerationRouteImport } from './routes/blog.temporary-email-lead-generation'
import { Route as BlogTemporaryEmailForumRegistrationRouteImport } from './routes/blog.temporary-email-forum-registration'
import { Route as BlogTemporaryEmailForVerificationGuideRouteImport } from './routes/blog.temporary-email-for-verification-guide'
import { Route as BlogTemporaryEmailForStudentsGuideRouteImport } from './routes/blog.temporary-email-for-students-guide'
import { Route as BlogTemporaryEmailForSocialMediaSignupRouteImport } from './routes/blog.temporary-email-for-social-media-signup'
import { Route as BlogTemporaryEmailForSigningUpRouteImport } from './routes/blog.temporary-email-for-signing-up'
import { Route as BlogTemporaryEmailForOnlinePrivacyRouteImport } from './routes/blog.temporary-email-for-online-privacy'
import { Route as BlogTemporaryEmailForGamingPlatformsRouteImport } from './routes/blog.temporary-email-for-gaming-platforms'
import { Route as BlogTemporaryEmailForDevelopersGuideRouteImport } from './routes/blog.temporary-email-for-developers-guide'
import { Route as BlogTemporaryEmailForClassifiedAdsRouteImport } from './routes/blog.temporary-email-for-classified-ads'
import { Route as BlogTemporaryEmailForBetaTestingRouteImport } from './routes/blog.temporary-email-for-beta-testing'
import { Route as BlogTemporaryEmailForAffiliateProgramsRouteImport } from './routes/blog.temporary-email-for-affiliate-programs'
import { Route as BlogTemporaryEmailEventRegistrationRouteImport } from './routes/blog.temporary-email-event-registration'
import { Route as BlogTemporaryEmailDatingAppsPrivacyGuideRouteImport } from './routes/blog.temporary-email-dating-apps-privacy-guide'
import { Route as BlogTemporaryEmailAccountRecoveryRouteImport } from './routes/blog.temporary-email-account-recovery'
import { Route as BlogTempEmailTiktokInstagramRedditRouteImport } from './routes/blog.temp-email-tiktok-instagram-reddit'
import { Route as BlogTempEmailChatgptClaudeCodexRouteImport } from './routes/blog.temp-email-chatgpt-claude-codex'
import { Route as BlogPlatformsBlockingTempEmail2026RouteImport } from './routes/blog.platforms-blocking-temp-email-2026'
import { Route as BlogIsTemporaryEmailSafeGuideRouteImport } from './routes/blog.is-temporary-email-safe-guide'
import { Route as BlogIsTemporaryEmailLegalRouteImport } from './routes/blog.is-temporary-email-legal'
import { Route as BlogHowToUseTemporaryEmailForTestingSoftwareRouteImport } from './routes/blog.how-to-use-temporary-email-for-testing-software'
import { Route as BlogHowToUseAnonymousEmailForMarketResearchRouteImport } from './routes/blog.how-to-use-anonymous-email-for-market-research'
import { Route as BlogHowToCreateTemporaryEmailGuideRouteImport } from './routes/blog.how-to-create-temporary-email-guide'
import { Route as BlogEmailPrivacyForSmallBusinessesGuideRouteImport } from './routes/blog.email-privacy-for-small-businesses-guide'
import { Route as BlogDisposableEmailWebinarRegistrationRouteImport } from './routes/blog.disposable-email-webinar-registration'
import { Route as BlogDisposableEmailSpamProtectionGuideRouteImport } from './routes/blog.disposable-email-spam-protection-guide'
import { Route as BlogDisposableEmailSecurityTestingGuideRouteImport } from './routes/blog.disposable-email-security-testing-guide'
import { Route as BlogDisposableEmailLoyaltyProgramsRouteImport } from './routes/blog.disposable-email-loyalty-programs'
import { Route as BlogDisposableEmailForSweepstakesGuideRouteImport } from './routes/blog.disposable-email-for-sweepstakes-guide'
import { Route as BlogDisposableEmailForSpamProtectionGuideRouteImport } from './routes/blog.disposable-email-for-spam-protection-guide'
import { Route as BlogDisposableEmailForFreelancersRouteImport } from './routes/blog.disposable-email-for-freelancers'
import { Route as BlogDisposableEmailForFreeTrialsGuideRouteImport } from './routes/blog.disposable-email-for-free-trials-guide'
import { Route as BlogDisposableEmailForCouponCodesRouteImport } from './routes/blog.disposable-email-for-coupon-codes'
import { Route as BlogDisposableEmailForAppDownloadsRouteImport } from './routes/blog.disposable-email-for-app-downloads'
import { Route as BlogBestTemporaryEmailServices2026RouteImport } from './routes/blog.best-temporary-email-services-2026'
import { Route as BlogAnonymousEmailSurveyResponsesRouteImport } from './routes/blog.anonymous-email-survey-responses'
import { Route as BlogAnonymousEmailForWhistleblowersGuideRouteImport } from './routes/blog.anonymous-email-for-whistleblowers-guide'
import { Route as BlogAnonymousEmailForJobApplicationsGuideRouteImport } from './routes/blog.anonymous-email-for-job-applications-guide'
import { Route as BlogAnonymousEmailForFeedbackFormsRouteImport } from './routes/blog.anonymous-email-for-feedback-forms'
import { Route as BlogAnonymousEmailForContactFormsRouteImport } from './routes/blog.anonymous-email-for-contact-forms'
import { Route as BlogAnonymousEmailCustomerSupportGuideRouteImport } from './routes/blog.anonymous-email-customer-support-guide'
import { Route as Blog6BillionEmailsLeaked2026RouteImport } from './routes/blog.6-billion-emails-leaked-2026'
import { Route as Blog12PercentSignupsUseTempEmailRouteImport } from './routes/blog.12-percent-signups-use-temp-email'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogUsingDisposableEmailForNewsletterSignupRoute =
  BlogUsingDisposableEmailForNewsletterSignupRouteImport.update({
    id: '/using-disposable-email-for-newsletter-signup',
    path: '/using-disposable-email-for-newsletter-signup',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailVsPermanentEmailDifferencesRoute =
  BlogTemporaryEmailVsPermanentEmailDifferencesRouteImport.update({
    id: '/temporary-email-vs-permanent-email-differences',
    path: '/temporary-email-vs-permanent-email-differences',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailSoftwareTrialsRoute =
  BlogTemporaryEmailSoftwareTrialsRouteImport.update({
    id: '/temporary-email-software-trials',
    path: '/temporary-email-software-trials',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailSaasSignupGuideRoute =
  BlogTemporaryEmailSaasSignupGuideRouteImport.update({
    id: '/temporary-email-saas-signup-guide',
    path: '/temporary-email-saas-signup-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailPrivacyProtectionGuideRoute =
  BlogTemporaryEmailPrivacyProtectionGuideRouteImport.update({
    id: '/temporary-email-privacy-protection-guide',
    path: '/temporary-email-privacy-protection-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailOnlinePrivacyGuideRoute =
  BlogTemporaryEmailOnlinePrivacyGuideRouteImport.update({
    id: '/temporary-email-online-privacy-guide',
    path: '/temporary-email-online-privacy-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailMembershipSitesGuideRoute =
  BlogTemporaryEmailMembershipSitesGuideRouteImport.update({
    id: '/temporary-email-membership-sites-guide',
    path: '/temporary-email-membership-sites-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailLeadGenerationRoute =
  BlogTemporaryEmailLeadGenerationRouteImport.update({
    id: '/temporary-email-lead-generation',
    path: '/temporary-email-lead-generation',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForumRegistrationRoute =
  BlogTemporaryEmailForumRegistrationRouteImport.update({
    id: '/temporary-email-forum-registration',
    path: '/temporary-email-forum-registration',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForVerificationGuideRoute =
  BlogTemporaryEmailForVerificationGuideRouteImport.update({
    id: '/temporary-email-for-verification-guide',
    path: '/temporary-email-for-verification-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForStudentsGuideRoute =
  BlogTemporaryEmailForStudentsGuideRouteImport.update({
    id: '/temporary-email-for-students-guide',
    path: '/temporary-email-for-students-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForSocialMediaSignupRoute =
  BlogTemporaryEmailForSocialMediaSignupRouteImport.update({
    id: '/temporary-email-for-social-media-signup',
    path: '/temporary-email-for-social-media-signup',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForSigningUpRoute =
  BlogTemporaryEmailForSigningUpRouteImport.update({
    id: '/temporary-email-for-signing-up',
    path: '/temporary-email-for-signing-up',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForOnlinePrivacyRoute =
  BlogTemporaryEmailForOnlinePrivacyRouteImport.update({
    id: '/temporary-email-for-online-privacy',
    path: '/temporary-email-for-online-privacy',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForGamingPlatformsRoute =
  BlogTemporaryEmailForGamingPlatformsRouteImport.update({
    id: '/temporary-email-for-gaming-platforms',
    path: '/temporary-email-for-gaming-platforms',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForDevelopersGuideRoute =
  BlogTemporaryEmailForDevelopersGuideRouteImport.update({
    id: '/temporary-email-for-developers-guide',
    path: '/temporary-email-for-developers-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForClassifiedAdsRoute =
  BlogTemporaryEmailForClassifiedAdsRouteImport.update({
    id: '/temporary-email-for-classified-ads',
    path: '/temporary-email-for-classified-ads',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForBetaTestingRoute =
  BlogTemporaryEmailForBetaTestingRouteImport.update({
    id: '/temporary-email-for-beta-testing',
    path: '/temporary-email-for-beta-testing',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailForAffiliateProgramsRoute =
  BlogTemporaryEmailForAffiliateProgramsRouteImport.update({
    id: '/temporary-email-for-affiliate-programs',
    path: '/temporary-email-for-affiliate-programs',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailEventRegistrationRoute =
  BlogTemporaryEmailEventRegistrationRouteImport.update({
    id: '/temporary-email-event-registration',
    path: '/temporary-email-event-registration',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailDatingAppsPrivacyGuideRoute =
  BlogTemporaryEmailDatingAppsPrivacyGuideRouteImport.update({
    id: '/temporary-email-dating-apps-privacy-guide',
    path: '/temporary-email-dating-apps-privacy-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTemporaryEmailAccountRecoveryRoute =
  BlogTemporaryEmailAccountRecoveryRouteImport.update({
    id: '/temporary-email-account-recovery',
    path: '/temporary-email-account-recovery',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTempEmailTiktokInstagramRedditRoute =
  BlogTempEmailTiktokInstagramRedditRouteImport.update({
    id: '/temp-email-tiktok-instagram-reddit',
    path: '/temp-email-tiktok-instagram-reddit',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogTempEmailChatgptClaudeCodexRoute =
  BlogTempEmailChatgptClaudeCodexRouteImport.update({
    id: '/temp-email-chatgpt-claude-codex',
    path: '/temp-email-chatgpt-claude-codex',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogPlatformsBlockingTempEmail2026Route =
  BlogPlatformsBlockingTempEmail2026RouteImport.update({
    id: '/platforms-blocking-temp-email-2026',
    path: '/platforms-blocking-temp-email-2026',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogIsTemporaryEmailSafeGuideRoute =
  BlogIsTemporaryEmailSafeGuideRouteImport.update({
    id: '/is-temporary-email-safe-guide',
    path: '/is-temporary-email-safe-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogIsTemporaryEmailLegalRoute =
  BlogIsTemporaryEmailLegalRouteImport.update({
    id: '/is-temporary-email-legal',
    path: '/is-temporary-email-legal',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogHowToUseTemporaryEmailForTestingSoftwareRoute =
  BlogHowToUseTemporaryEmailForTestingSoftwareRouteImport.update({
    id: '/how-to-use-temporary-email-for-testing-software',
    path: '/how-to-use-temporary-email-for-testing-software',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogHowToUseAnonymousEmailForMarketResearchRoute =
  BlogHowToUseAnonymousEmailForMarketResearchRouteImport.update({
    id: '/how-to-use-anonymous-email-for-market-research',
    path: '/how-to-use-anonymous-email-for-market-research',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogHowToCreateTemporaryEmailGuideRoute =
  BlogHowToCreateTemporaryEmailGuideRouteImport.update({
    id: '/how-to-create-temporary-email-guide',
    path: '/how-to-create-temporary-email-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogEmailPrivacyForSmallBusinessesGuideRoute =
  BlogEmailPrivacyForSmallBusinessesGuideRouteImport.update({
    id: '/email-privacy-for-small-businesses-guide',
    path: '/email-privacy-for-small-businesses-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailWebinarRegistrationRoute =
  BlogDisposableEmailWebinarRegistrationRouteImport.update({
    id: '/disposable-email-webinar-registration',
    path: '/disposable-email-webinar-registration',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailSpamProtectionGuideRoute =
  BlogDisposableEmailSpamProtectionGuideRouteImport.update({
    id: '/disposable-email-spam-protection-guide',
    path: '/disposable-email-spam-protection-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailSecurityTestingGuideRoute =
  BlogDisposableEmailSecurityTestingGuideRouteImport.update({
    id: '/disposable-email-security-testing-guide',
    path: '/disposable-email-security-testing-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailLoyaltyProgramsRoute =
  BlogDisposableEmailLoyaltyProgramsRouteImport.update({
    id: '/disposable-email-loyalty-programs',
    path: '/disposable-email-loyalty-programs',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailForSweepstakesGuideRoute =
  BlogDisposableEmailForSweepstakesGuideRouteImport.update({
    id: '/disposable-email-for-sweepstakes-guide',
    path: '/disposable-email-for-sweepstakes-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailForSpamProtectionGuideRoute =
  BlogDisposableEmailForSpamProtectionGuideRouteImport.update({
    id: '/disposable-email-for-spam-protection-guide',
    path: '/disposable-email-for-spam-protection-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailForFreelancersRoute =
  BlogDisposableEmailForFreelancersRouteImport.update({
    id: '/disposable-email-for-freelancers',
    path: '/disposable-email-for-freelancers',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailForFreeTrialsGuideRoute =
  BlogDisposableEmailForFreeTrialsGuideRouteImport.update({
    id: '/disposable-email-for-free-trials-guide',
    path: '/disposable-email-for-free-trials-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailForCouponCodesRoute =
  BlogDisposableEmailForCouponCodesRouteImport.update({
    id: '/disposable-email-for-coupon-codes',
    path: '/disposable-email-for-coupon-codes',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDisposableEmailForAppDownloadsRoute =
  BlogDisposableEmailForAppDownloadsRouteImport.update({
    id: '/disposable-email-for-app-downloads',
    path: '/disposable-email-for-app-downloads',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogBestTemporaryEmailServices2026Route =
  BlogBestTemporaryEmailServices2026RouteImport.update({
    id: '/best-temporary-email-services-2026',
    path: '/best-temporary-email-services-2026',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogAnonymousEmailSurveyResponsesRoute =
  BlogAnonymousEmailSurveyResponsesRouteImport.update({
    id: '/anonymous-email-survey-responses',
    path: '/anonymous-email-survey-responses',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogAnonymousEmailForWhistleblowersGuideRoute =
  BlogAnonymousEmailForWhistleblowersGuideRouteImport.update({
    id: '/anonymous-email-for-whistleblowers-guide',
    path: '/anonymous-email-for-whistleblowers-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogAnonymousEmailForJobApplicationsGuideRoute =
  BlogAnonymousEmailForJobApplicationsGuideRouteImport.update({
    id: '/anonymous-email-for-job-applications-guide',
    path: '/anonymous-email-for-job-applications-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogAnonymousEmailForFeedbackFormsRoute =
  BlogAnonymousEmailForFeedbackFormsRouteImport.update({
    id: '/anonymous-email-for-feedback-forms',
    path: '/anonymous-email-for-feedback-forms',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogAnonymousEmailForContactFormsRoute =
  BlogAnonymousEmailForContactFormsRouteImport.update({
    id: '/anonymous-email-for-contact-forms',
    path: '/anonymous-email-for-contact-forms',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogAnonymousEmailCustomerSupportGuideRoute =
  BlogAnonymousEmailCustomerSupportGuideRouteImport.update({
    id: '/anonymous-email-customer-support-guide',
    path: '/anonymous-email-customer-support-guide',
    getParentRoute: () => BlogRoute,
  } as any)
const Blog6BillionEmailsLeaked2026Route =
  Blog6BillionEmailsLeaked2026RouteImport.update({
    id: '/6-billion-emails-leaked-2026',
    path: '/6-billion-emails-leaked-2026',
    getParentRoute: () => BlogRoute,
  } as any)
const Blog12PercentSignupsUseTempEmailRoute =
  Blog12PercentSignupsUseTempEmailRouteImport.update({
    id: '/12-percent-signups-use-temp-email',
    path: '/12-percent-signups-use-temp-email',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/12-percent-signups-use-temp-email': typeof Blog12PercentSignupsUseTempEmailRoute
  '/blog/6-billion-emails-leaked-2026': typeof Blog6BillionEmailsLeaked2026Route
  '/blog/anonymous-email-customer-support-guide': typeof BlogAnonymousEmailCustomerSupportGuideRoute
  '/blog/anonymous-email-for-contact-forms': typeof BlogAnonymousEmailForContactFormsRoute
  '/blog/anonymous-email-for-feedback-forms': typeof BlogAnonymousEmailForFeedbackFormsRoute
  '/blog/anonymous-email-for-job-applications-guide': typeof BlogAnonymousEmailForJobApplicationsGuideRoute
  '/blog/anonymous-email-for-whistleblowers-guide': typeof BlogAnonymousEmailForWhistleblowersGuideRoute
  '/blog/anonymous-email-survey-responses': typeof BlogAnonymousEmailSurveyResponsesRoute
  '/blog/best-temporary-email-services-2026': typeof BlogBestTemporaryEmailServices2026Route
  '/blog/disposable-email-for-app-downloads': typeof BlogDisposableEmailForAppDownloadsRoute
  '/blog/disposable-email-for-coupon-codes': typeof BlogDisposableEmailForCouponCodesRoute
  '/blog/disposable-email-for-free-trials-guide': typeof BlogDisposableEmailForFreeTrialsGuideRoute
  '/blog/disposable-email-for-freelancers': typeof BlogDisposableEmailForFreelancersRoute
  '/blog/disposable-email-for-spam-protection-guide': typeof BlogDisposableEmailForSpamProtectionGuideRoute
  '/blog/disposable-email-for-sweepstakes-guide': typeof BlogDisposableEmailForSweepstakesGuideRoute
  '/blog/disposable-email-loyalty-programs': typeof BlogDisposableEmailLoyaltyProgramsRoute
  '/blog/disposable-email-security-testing-guide': typeof BlogDisposableEmailSecurityTestingGuideRoute
  '/blog/disposable-email-spam-protection-guide': typeof BlogDisposableEmailSpamProtectionGuideRoute
  '/blog/disposable-email-webinar-registration': typeof BlogDisposableEmailWebinarRegistrationRoute
  '/blog/email-privacy-for-small-businesses-guide': typeof BlogEmailPrivacyForSmallBusinessesGuideRoute
  '/blog/how-to-create-temporary-email-guide': typeof BlogHowToCreateTemporaryEmailGuideRoute
  '/blog/how-to-use-anonymous-email-for-market-research': typeof BlogHowToUseAnonymousEmailForMarketResearchRoute
  '/blog/how-to-use-temporary-email-for-testing-software': typeof BlogHowToUseTemporaryEmailForTestingSoftwareRoute
  '/blog/is-temporary-email-legal': typeof BlogIsTemporaryEmailLegalRoute
  '/blog/is-temporary-email-safe-guide': typeof BlogIsTemporaryEmailSafeGuideRoute
  '/blog/platforms-blocking-temp-email-2026': typeof BlogPlatformsBlockingTempEmail2026Route
  '/blog/temp-email-chatgpt-claude-codex': typeof BlogTempEmailChatgptClaudeCodexRoute
  '/blog/temp-email-tiktok-instagram-reddit': typeof BlogTempEmailTiktokInstagramRedditRoute
  '/blog/temporary-email-account-recovery': typeof BlogTemporaryEmailAccountRecoveryRoute
  '/blog/temporary-email-dating-apps-privacy-guide': typeof BlogTemporaryEmailDatingAppsPrivacyGuideRoute
  '/blog/temporary-email-event-registration': typeof BlogTemporaryEmailEventRegistrationRoute
  '/blog/temporary-email-for-affiliate-programs': typeof BlogTemporaryEmailForAffiliateProgramsRoute
  '/blog/temporary-email-for-beta-testing': typeof BlogTemporaryEmailForBetaTestingRoute
  '/blog/temporary-email-for-classified-ads': typeof BlogTemporaryEmailForClassifiedAdsRoute
  '/blog/temporary-email-for-developers-guide': typeof BlogTemporaryEmailForDevelopersGuideRoute
  '/blog/temporary-email-for-gaming-platforms': typeof BlogTemporaryEmailForGamingPlatformsRoute
  '/blog/temporary-email-for-online-privacy': typeof BlogTemporaryEmailForOnlinePrivacyRoute
  '/blog/temporary-email-for-signing-up': typeof BlogTemporaryEmailForSigningUpRoute
  '/blog/temporary-email-for-social-media-signup': typeof BlogTemporaryEmailForSocialMediaSignupRoute
  '/blog/temporary-email-for-students-guide': typeof BlogTemporaryEmailForStudentsGuideRoute
  '/blog/temporary-email-for-verification-guide': typeof BlogTemporaryEmailForVerificationGuideRoute
  '/blog/temporary-email-forum-registration': typeof BlogTemporaryEmailForumRegistrationRoute
  '/blog/temporary-email-lead-generation': typeof BlogTemporaryEmailLeadGenerationRoute
  '/blog/temporary-email-membership-sites-guide': typeof BlogTemporaryEmailMembershipSitesGuideRoute
  '/blog/temporary-email-online-privacy-guide': typeof BlogTemporaryEmailOnlinePrivacyGuideRoute
  '/blog/temporary-email-privacy-protection-guide': typeof BlogTemporaryEmailPrivacyProtectionGuideRoute
  '/blog/temporary-email-saas-signup-guide': typeof BlogTemporaryEmailSaasSignupGuideRoute
  '/blog/temporary-email-software-trials': typeof BlogTemporaryEmailSoftwareTrialsRoute
  '/blog/temporary-email-vs-permanent-email-differences': typeof BlogTemporaryEmailVsPermanentEmailDifferencesRoute
  '/blog/using-disposable-email-for-newsletter-signup': typeof BlogUsingDisposableEmailForNewsletterSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/12-percent-signups-use-temp-email': typeof Blog12PercentSignupsUseTempEmailRoute
  '/blog/6-billion-emails-leaked-2026': typeof Blog6BillionEmailsLeaked2026Route
  '/blog/anonymous-email-customer-support-guide': typeof BlogAnonymousEmailCustomerSupportGuideRoute
  '/blog/anonymous-email-for-contact-forms': typeof BlogAnonymousEmailForContactFormsRoute
  '/blog/anonymous-email-for-feedback-forms': typeof BlogAnonymousEmailForFeedbackFormsRoute
  '/blog/anonymous-email-for-job-applications-guide': typeof BlogAnonymousEmailForJobApplicationsGuideRoute
  '/blog/anonymous-email-for-whistleblowers-guide': typeof BlogAnonymousEmailForWhistleblowersGuideRoute
  '/blog/anonymous-email-survey-responses': typeof BlogAnonymousEmailSurveyResponsesRoute
  '/blog/best-temporary-email-services-2026': typeof BlogBestTemporaryEmailServices2026Route
  '/blog/disposable-email-for-app-downloads': typeof BlogDisposableEmailForAppDownloadsRoute
  '/blog/disposable-email-for-coupon-codes': typeof BlogDisposableEmailForCouponCodesRoute
  '/blog/disposable-email-for-free-trials-guide': typeof BlogDisposableEmailForFreeTrialsGuideRoute
  '/blog/disposable-email-for-freelancers': typeof BlogDisposableEmailForFreelancersRoute
  '/blog/disposable-email-for-spam-protection-guide': typeof BlogDisposableEmailForSpamProtectionGuideRoute
  '/blog/disposable-email-for-sweepstakes-guide': typeof BlogDisposableEmailForSweepstakesGuideRoute
  '/blog/disposable-email-loyalty-programs': typeof BlogDisposableEmailLoyaltyProgramsRoute
  '/blog/disposable-email-security-testing-guide': typeof BlogDisposableEmailSecurityTestingGuideRoute
  '/blog/disposable-email-spam-protection-guide': typeof BlogDisposableEmailSpamProtectionGuideRoute
  '/blog/disposable-email-webinar-registration': typeof BlogDisposableEmailWebinarRegistrationRoute
  '/blog/email-privacy-for-small-businesses-guide': typeof BlogEmailPrivacyForSmallBusinessesGuideRoute
  '/blog/how-to-create-temporary-email-guide': typeof BlogHowToCreateTemporaryEmailGuideRoute
  '/blog/how-to-use-anonymous-email-for-market-research': typeof BlogHowToUseAnonymousEmailForMarketResearchRoute
  '/blog/how-to-use-temporary-email-for-testing-software': typeof BlogHowToUseTemporaryEmailForTestingSoftwareRoute
  '/blog/is-temporary-email-legal': typeof BlogIsTemporaryEmailLegalRoute
  '/blog/is-temporary-email-safe-guide': typeof BlogIsTemporaryEmailSafeGuideRoute
  '/blog/platforms-blocking-temp-email-2026': typeof BlogPlatformsBlockingTempEmail2026Route
  '/blog/temp-email-chatgpt-claude-codex': typeof BlogTempEmailChatgptClaudeCodexRoute
  '/blog/temp-email-tiktok-instagram-reddit': typeof BlogTempEmailTiktokInstagramRedditRoute
  '/blog/temporary-email-account-recovery': typeof BlogTemporaryEmailAccountRecoveryRoute
  '/blog/temporary-email-dating-apps-privacy-guide': typeof BlogTemporaryEmailDatingAppsPrivacyGuideRoute
  '/blog/temporary-email-event-registration': typeof BlogTemporaryEmailEventRegistrationRoute
  '/blog/temporary-email-for-affiliate-programs': typeof BlogTemporaryEmailForAffiliateProgramsRoute
  '/blog/temporary-email-for-beta-testing': typeof BlogTemporaryEmailForBetaTestingRoute
  '/blog/temporary-email-for-classified-ads': typeof BlogTemporaryEmailForClassifiedAdsRoute
  '/blog/temporary-email-for-developers-guide': typeof BlogTemporaryEmailForDevelopersGuideRoute
  '/blog/temporary-email-for-gaming-platforms': typeof BlogTemporaryEmailForGamingPlatformsRoute
  '/blog/temporary-email-for-online-privacy': typeof BlogTemporaryEmailForOnlinePrivacyRoute
  '/blog/temporary-email-for-signing-up': typeof BlogTemporaryEmailForSigningUpRoute
  '/blog/temporary-email-for-social-media-signup': typeof BlogTemporaryEmailForSocialMediaSignupRoute
  '/blog/temporary-email-for-students-guide': typeof BlogTemporaryEmailForStudentsGuideRoute
  '/blog/temporary-email-for-verification-guide': typeof BlogTemporaryEmailForVerificationGuideRoute
  '/blog/temporary-email-forum-registration': typeof BlogTemporaryEmailForumRegistrationRoute
  '/blog/temporary-email-lead-generation': typeof BlogTemporaryEmailLeadGenerationRoute
  '/blog/temporary-email-membership-sites-guide': typeof BlogTemporaryEmailMembershipSitesGuideRoute
  '/blog/temporary-email-online-privacy-guide': typeof BlogTemporaryEmailOnlinePrivacyGuideRoute
  '/blog/temporary-email-privacy-protection-guide': typeof BlogTemporaryEmailPrivacyProtectionGuideRoute
  '/blog/temporary-email-saas-signup-guide': typeof BlogTemporaryEmailSaasSignupGuideRoute
  '/blog/temporary-email-software-trials': typeof BlogTemporaryEmailSoftwareTrialsRoute
  '/blog/temporary-email-vs-permanent-email-differences': typeof BlogTemporaryEmailVsPermanentEmailDifferencesRoute
  '/blog/using-disposable-email-for-newsletter-signup': typeof BlogUsingDisposableEmailForNewsletterSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/12-percent-signups-use-temp-email': typeof Blog12PercentSignupsUseTempEmailRoute
  '/blog/6-billion-emails-leaked-2026': typeof Blog6BillionEmailsLeaked2026Route
  '/blog/anonymous-email-customer-support-guide': typeof BlogAnonymousEmailCustomerSupportGuideRoute
  '/blog/anonymous-email-for-contact-forms': typeof BlogAnonymousEmailForContactFormsRoute
  '/blog/anonymous-email-for-feedback-forms': typeof BlogAnonymousEmailForFeedbackFormsRoute
  '/blog/anonymous-email-for-job-applications-guide': typeof BlogAnonymousEmailForJobApplicationsGuideRoute
  '/blog/anonymous-email-for-whistleblowers-guide': typeof BlogAnonymousEmailForWhistleblowersGuideRoute
  '/blog/anonymous-email-survey-responses': typeof BlogAnonymousEmailSurveyResponsesRoute
  '/blog/best-temporary-email-services-2026': typeof BlogBestTemporaryEmailServices2026Route
  '/blog/disposable-email-for-app-downloads': typeof BlogDisposableEmailForAppDownloadsRoute
  '/blog/disposable-email-for-coupon-codes': typeof BlogDisposableEmailForCouponCodesRoute
  '/blog/disposable-email-for-free-trials-guide': typeof BlogDisposableEmailForFreeTrialsGuideRoute
  '/blog/disposable-email-for-freelancers': typeof BlogDisposableEmailForFreelancersRoute
  '/blog/disposable-email-for-spam-protection-guide': typeof BlogDisposableEmailForSpamProtectionGuideRoute
  '/blog/disposable-email-for-sweepstakes-guide': typeof BlogDisposableEmailForSweepstakesGuideRoute
  '/blog/disposable-email-loyalty-programs': typeof BlogDisposableEmailLoyaltyProgramsRoute
  '/blog/disposable-email-security-testing-guide': typeof BlogDisposableEmailSecurityTestingGuideRoute
  '/blog/disposable-email-spam-protection-guide': typeof BlogDisposableEmailSpamProtectionGuideRoute
  '/blog/disposable-email-webinar-registration': typeof BlogDisposableEmailWebinarRegistrationRoute
  '/blog/email-privacy-for-small-businesses-guide': typeof BlogEmailPrivacyForSmallBusinessesGuideRoute
  '/blog/how-to-create-temporary-email-guide': typeof BlogHowToCreateTemporaryEmailGuideRoute
  '/blog/how-to-use-anonymous-email-for-market-research': typeof BlogHowToUseAnonymousEmailForMarketResearchRoute
  '/blog/how-to-use-temporary-email-for-testing-software': typeof BlogHowToUseTemporaryEmailForTestingSoftwareRoute
  '/blog/is-temporary-email-legal': typeof BlogIsTemporaryEmailLegalRoute
  '/blog/is-temporary-email-safe-guide': typeof BlogIsTemporaryEmailSafeGuideRoute
  '/blog/platforms-blocking-temp-email-2026': typeof BlogPlatformsBlockingTempEmail2026Route
  '/blog/temp-email-chatgpt-claude-codex': typeof BlogTempEmailChatgptClaudeCodexRoute
  '/blog/temp-email-tiktok-instagram-reddit': typeof BlogTempEmailTiktokInstagramRedditRoute
  '/blog/temporary-email-account-recovery': typeof BlogTemporaryEmailAccountRecoveryRoute
  '/blog/temporary-email-dating-apps-privacy-guide': typeof BlogTemporaryEmailDatingAppsPrivacyGuideRoute
  '/blog/temporary-email-event-registration': typeof BlogTemporaryEmailEventRegistrationRoute
  '/blog/temporary-email-for-affiliate-programs': typeof BlogTemporaryEmailForAffiliateProgramsRoute
  '/blog/temporary-email-for-beta-testing': typeof BlogTemporaryEmailForBetaTestingRoute
  '/blog/temporary-email-for-classified-ads': typeof BlogTemporaryEmailForClassifiedAdsRoute
  '/blog/temporary-email-for-developers-guide': typeof BlogTemporaryEmailForDevelopersGuideRoute
  '/blog/temporary-email-for-gaming-platforms': typeof BlogTemporaryEmailForGamingPlatformsRoute
  '/blog/temporary-email-for-online-privacy': typeof BlogTemporaryEmailForOnlinePrivacyRoute
  '/blog/temporary-email-for-signing-up': typeof BlogTemporaryEmailForSigningUpRoute
  '/blog/temporary-email-for-social-media-signup': typeof BlogTemporaryEmailForSocialMediaSignupRoute
  '/blog/temporary-email-for-students-guide': typeof BlogTemporaryEmailForStudentsGuideRoute
  '/blog/temporary-email-for-verification-guide': typeof BlogTemporaryEmailForVerificationGuideRoute
  '/blog/temporary-email-forum-registration': typeof BlogTemporaryEmailForumRegistrationRoute
  '/blog/temporary-email-lead-generation': typeof BlogTemporaryEmailLeadGenerationRoute
  '/blog/temporary-email-membership-sites-guide': typeof BlogTemporaryEmailMembershipSitesGuideRoute
  '/blog/temporary-email-online-privacy-guide': typeof BlogTemporaryEmailOnlinePrivacyGuideRoute
  '/blog/temporary-email-privacy-protection-guide': typeof BlogTemporaryEmailPrivacyProtectionGuideRoute
  '/blog/temporary-email-saas-signup-guide': typeof BlogTemporaryEmailSaasSignupGuideRoute
  '/blog/temporary-email-software-trials': typeof BlogTemporaryEmailSoftwareTrialsRoute
  '/blog/temporary-email-vs-permanent-email-differences': typeof BlogTemporaryEmailVsPermanentEmailDifferencesRoute
  '/blog/using-disposable-email-for-newsletter-signup': typeof BlogUsingDisposableEmailForNewsletterSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/blog'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/blog/12-percent-signups-use-temp-email'
    | '/blog/6-billion-emails-leaked-2026'
    | '/blog/anonymous-email-customer-support-guide'
    | '/blog/anonymous-email-for-contact-forms'
    | '/blog/anonymous-email-for-feedback-forms'
    | '/blog/anonymous-email-for-job-applications-guide'
    | '/blog/anonymous-email-for-whistleblowers-guide'
    | '/blog/anonymous-email-survey-responses'
    | '/blog/best-temporary-email-services-2026'
    | '/blog/disposable-email-for-app-downloads'
    | '/blog/disposable-email-for-coupon-codes'
    | '/blog/disposable-email-for-free-trials-guide'
    | '/blog/disposable-email-for-freelancers'
    | '/blog/disposable-email-for-spam-protection-guide'
    | '/blog/disposable-email-for-sweepstakes-guide'
    | '/blog/disposable-email-loyalty-programs'
    | '/blog/disposable-email-security-testing-guide'
    | '/blog/disposable-email-spam-protection-guide'
    | '/blog/disposable-email-webinar-registration'
    | '/blog/email-privacy-for-small-businesses-guide'
    | '/blog/how-to-create-temporary-email-guide'
    | '/blog/how-to-use-anonymous-email-for-market-research'
    | '/blog/how-to-use-temporary-email-for-testing-software'
    | '/blog/is-temporary-email-legal'
    | '/blog/is-temporary-email-safe-guide'
    | '/blog/platforms-blocking-temp-email-2026'
    | '/blog/temp-email-chatgpt-claude-codex'
    | '/blog/temp-email-tiktok-instagram-reddit'
    | '/blog/temporary-email-account-recovery'
    | '/blog/temporary-email-dating-apps-privacy-guide'
    | '/blog/temporary-email-event-registration'
    | '/blog/temporary-email-for-affiliate-programs'
    | '/blog/temporary-email-for-beta-testing'
    | '/blog/temporary-email-for-classified-ads'
    | '/blog/temporary-email-for-developers-guide'
    | '/blog/temporary-email-for-gaming-platforms'
    | '/blog/temporary-email-for-online-privacy'
    | '/blog/temporary-email-for-signing-up'
    | '/blog/temporary-email-for-social-media-signup'
    | '/blog/temporary-email-for-students-guide'
    | '/blog/temporary-email-for-verification-guide'
    | '/blog/temporary-email-forum-registration'
    | '/blog/temporary-email-lead-generation'
    | '/blog/temporary-email-membership-sites-guide'
    | '/blog/temporary-email-online-privacy-guide'
    | '/blog/temporary-email-privacy-protection-guide'
    | '/blog/temporary-email-saas-signup-guide'
    | '/blog/temporary-email-software-trials'
    | '/blog/temporary-email-vs-permanent-email-differences'
    | '/blog/using-disposable-email-for-newsletter-signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/blog'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/blog/12-percent-signups-use-temp-email'
    | '/blog/6-billion-emails-leaked-2026'
    | '/blog/anonymous-email-customer-support-guide'
    | '/blog/anonymous-email-for-contact-forms'
    | '/blog/anonymous-email-for-feedback-forms'
    | '/blog/anonymous-email-for-job-applications-guide'
    | '/blog/anonymous-email-for-whistleblowers-guide'
    | '/blog/anonymous-email-survey-responses'
    | '/blog/best-temporary-email-services-2026'
    | '/blog/disposable-email-for-app-downloads'
    | '/blog/disposable-email-for-coupon-codes'
    | '/blog/disposable-email-for-free-trials-guide'
    | '/blog/disposable-email-for-freelancers'
    | '/blog/disposable-email-for-spam-protection-guide'
    | '/blog/disposable-email-for-sweepstakes-guide'
    | '/blog/disposable-email-loyalty-programs'
    | '/blog/disposable-email-security-testing-guide'
    | '/blog/disposable-email-spam-protection-guide'
    | '/blog/disposable-email-webinar-registration'
    | '/blog/email-privacy-for-small-businesses-guide'
    | '/blog/how-to-create-temporary-email-guide'
    | '/blog/how-to-use-anonymous-email-for-market-research'
    | '/blog/how-to-use-temporary-email-for-testing-software'
    | '/blog/is-temporary-email-legal'
    | '/blog/is-temporary-email-safe-guide'
    | '/blog/platforms-blocking-temp-email-2026'
    | '/blog/temp-email-chatgpt-claude-codex'
    | '/blog/temp-email-tiktok-instagram-reddit'
    | '/blog/temporary-email-account-recovery'
    | '/blog/temporary-email-dating-apps-privacy-guide'
    | '/blog/temporary-email-event-registration'
    | '/blog/temporary-email-for-affiliate-programs'
    | '/blog/temporary-email-for-beta-testing'
    | '/blog/temporary-email-for-classified-ads'
    | '/blog/temporary-email-for-developers-guide'
    | '/blog/temporary-email-for-gaming-platforms'
    | '/blog/temporary-email-for-online-privacy'
    | '/blog/temporary-email-for-signing-up'
    | '/blog/temporary-email-for-social-media-signup'
    | '/blog/temporary-email-for-students-guide'
    | '/blog/temporary-email-for-verification-guide'
    | '/blog/temporary-email-forum-registration'
    | '/blog/temporary-email-lead-generation'
    | '/blog/temporary-email-membership-sites-guide'
    | '/blog/temporary-email-online-privacy-guide'
    | '/blog/temporary-email-privacy-protection-guide'
    | '/blog/temporary-email-saas-signup-guide'
    | '/blog/temporary-email-software-trials'
    | '/blog/temporary-email-vs-permanent-email-differences'
    | '/blog/using-disposable-email-for-newsletter-signup'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/blog'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/blog/12-percent-signups-use-temp-email'
    | '/blog/6-billion-emails-leaked-2026'
    | '/blog/anonymous-email-customer-support-guide'
    | '/blog/anonymous-email-for-contact-forms'
    | '/blog/anonymous-email-for-feedback-forms'
    | '/blog/anonymous-email-for-job-applications-guide'
    | '/blog/anonymous-email-for-whistleblowers-guide'
    | '/blog/anonymous-email-survey-responses'
    | '/blog/best-temporary-email-services-2026'
    | '/blog/disposable-email-for-app-downloads'
    | '/blog/disposable-email-for-coupon-codes'
    | '/blog/disposable-email-for-free-trials-guide'
    | '/blog/disposable-email-for-freelancers'
    | '/blog/disposable-email-for-spam-protection-guide'
    | '/blog/disposable-email-for-sweepstakes-guide'
    | '/blog/disposable-email-loyalty-programs'
    | '/blog/disposable-email-security-testing-guide'
    | '/blog/disposable-email-spam-protection-guide'
    | '/blog/disposable-email-webinar-registration'
    | '/blog/email-privacy-for-small-businesses-guide'
    | '/blog/how-to-create-temporary-email-guide'
    | '/blog/how-to-use-anonymous-email-for-market-research'
    | '/blog/how-to-use-temporary-email-for-testing-software'
    | '/blog/is-temporary-email-legal'
    | '/blog/is-temporary-email-safe-guide'
    | '/blog/platforms-blocking-temp-email-2026'
    | '/blog/temp-email-chatgpt-claude-codex'
    | '/blog/temp-email-tiktok-instagram-reddit'
    | '/blog/temporary-email-account-recovery'
    | '/blog/temporary-email-dating-apps-privacy-guide'
    | '/blog/temporary-email-event-registration'
    | '/blog/temporary-email-for-affiliate-programs'
    | '/blog/temporary-email-for-beta-testing'
    | '/blog/temporary-email-for-classified-ads'
    | '/blog/temporary-email-for-developers-guide'
    | '/blog/temporary-email-for-gaming-platforms'
    | '/blog/temporary-email-for-online-privacy'
    | '/blog/temporary-email-for-signing-up'
    | '/blog/temporary-email-for-social-media-signup'
    | '/blog/temporary-email-for-students-guide'
    | '/blog/temporary-email-for-verification-guide'
    | '/blog/temporary-email-forum-registration'
    | '/blog/temporary-email-lead-generation'
    | '/blog/temporary-email-membership-sites-guide'
    | '/blog/temporary-email-online-privacy-guide'
    | '/blog/temporary-email-privacy-protection-guide'
    | '/blog/temporary-email-saas-signup-guide'
    | '/blog/temporary-email-software-trials'
    | '/blog/temporary-email-vs-permanent-email-differences'
    | '/blog/using-disposable-email-for-newsletter-signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BlogRoute: typeof BlogRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/using-disposable-email-for-newsletter-signup': {
      id: '/blog/using-disposable-email-for-newsletter-signup'
      path: '/using-disposable-email-for-newsletter-signup'
      fullPath: '/blog/using-disposable-email-for-newsletter-signup'
      preLoaderRoute: typeof BlogUsingDisposableEmailForNewsletterSignupRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-vs-permanent-email-differences': {
      id: '/blog/temporary-email-vs-permanent-email-differences'
      path: '/temporary-email-vs-permanent-email-differences'
      fullPath: '/blog/temporary-email-vs-permanent-email-differences'
      preLoaderRoute: typeof BlogTemporaryEmailVsPermanentEmailDifferencesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-software-trials': {
      id: '/blog/temporary-email-software-trials'
      path: '/temporary-email-software-trials'
      fullPath: '/blog/temporary-email-software-trials'
      preLoaderRoute: typeof BlogTemporaryEmailSoftwareTrialsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-saas-signup-guide': {
      id: '/blog/temporary-email-saas-signup-guide'
      path: '/temporary-email-saas-signup-guide'
      fullPath: '/blog/temporary-email-saas-signup-guide'
      preLoaderRoute: typeof BlogTemporaryEmailSaasSignupGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-privacy-protection-guide': {
      id: '/blog/temporary-email-privacy-protection-guide'
      path: '/temporary-email-privacy-protection-guide'
      fullPath: '/blog/temporary-email-privacy-protection-guide'
      preLoaderRoute: typeof BlogTemporaryEmailPrivacyProtectionGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-online-privacy-guide': {
      id: '/blog/temporary-email-online-privacy-guide'
      path: '/temporary-email-online-privacy-guide'
      fullPath: '/blog/temporary-email-online-privacy-guide'
      preLoaderRoute: typeof BlogTemporaryEmailOnlinePrivacyGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-membership-sites-guide': {
      id: '/blog/temporary-email-membership-sites-guide'
      path: '/temporary-email-membership-sites-guide'
      fullPath: '/blog/temporary-email-membership-sites-guide'
      preLoaderRoute: typeof BlogTemporaryEmailMembershipSitesGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-lead-generation': {
      id: '/blog/temporary-email-lead-generation'
      path: '/temporary-email-lead-generation'
      fullPath: '/blog/temporary-email-lead-generation'
      preLoaderRoute: typeof BlogTemporaryEmailLeadGenerationRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-forum-registration': {
      id: '/blog/temporary-email-forum-registration'
      path: '/temporary-email-forum-registration'
      fullPath: '/blog/temporary-email-forum-registration'
      preLoaderRoute: typeof BlogTemporaryEmailForumRegistrationRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-verification-guide': {
      id: '/blog/temporary-email-for-verification-guide'
      path: '/temporary-email-for-verification-guide'
      fullPath: '/blog/temporary-email-for-verification-guide'
      preLoaderRoute: typeof BlogTemporaryEmailForVerificationGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-students-guide': {
      id: '/blog/temporary-email-for-students-guide'
      path: '/temporary-email-for-students-guide'
      fullPath: '/blog/temporary-email-for-students-guide'
      preLoaderRoute: typeof BlogTemporaryEmailForStudentsGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-social-media-signup': {
      id: '/blog/temporary-email-for-social-media-signup'
      path: '/temporary-email-for-social-media-signup'
      fullPath: '/blog/temporary-email-for-social-media-signup'
      preLoaderRoute: typeof BlogTemporaryEmailForSocialMediaSignupRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-signing-up': {
      id: '/blog/temporary-email-for-signing-up'
      path: '/temporary-email-for-signing-up'
      fullPath: '/blog/temporary-email-for-signing-up'
      preLoaderRoute: typeof BlogTemporaryEmailForSigningUpRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-online-privacy': {
      id: '/blog/temporary-email-for-online-privacy'
      path: '/temporary-email-for-online-privacy'
      fullPath: '/blog/temporary-email-for-online-privacy'
      preLoaderRoute: typeof BlogTemporaryEmailForOnlinePrivacyRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-gaming-platforms': {
      id: '/blog/temporary-email-for-gaming-platforms'
      path: '/temporary-email-for-gaming-platforms'
      fullPath: '/blog/temporary-email-for-gaming-platforms'
      preLoaderRoute: typeof BlogTemporaryEmailForGamingPlatformsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-developers-guide': {
      id: '/blog/temporary-email-for-developers-guide'
      path: '/temporary-email-for-developers-guide'
      fullPath: '/blog/temporary-email-for-developers-guide'
      preLoaderRoute: typeof BlogTemporaryEmailForDevelopersGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-classified-ads': {
      id: '/blog/temporary-email-for-classified-ads'
      path: '/temporary-email-for-classified-ads'
      fullPath: '/blog/temporary-email-for-classified-ads'
      preLoaderRoute: typeof BlogTemporaryEmailForClassifiedAdsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-beta-testing': {
      id: '/blog/temporary-email-for-beta-testing'
      path: '/temporary-email-for-beta-testing'
      fullPath: '/blog/temporary-email-for-beta-testing'
      preLoaderRoute: typeof BlogTemporaryEmailForBetaTestingRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-for-affiliate-programs': {
      id: '/blog/temporary-email-for-affiliate-programs'
      path: '/temporary-email-for-affiliate-programs'
      fullPath: '/blog/temporary-email-for-affiliate-programs'
      preLoaderRoute: typeof BlogTemporaryEmailForAffiliateProgramsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-event-registration': {
      id: '/blog/temporary-email-event-registration'
      path: '/temporary-email-event-registration'
      fullPath: '/blog/temporary-email-event-registration'
      preLoaderRoute: typeof BlogTemporaryEmailEventRegistrationRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-dating-apps-privacy-guide': {
      id: '/blog/temporary-email-dating-apps-privacy-guide'
      path: '/temporary-email-dating-apps-privacy-guide'
      fullPath: '/blog/temporary-email-dating-apps-privacy-guide'
      preLoaderRoute: typeof BlogTemporaryEmailDatingAppsPrivacyGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temporary-email-account-recovery': {
      id: '/blog/temporary-email-account-recovery'
      path: '/temporary-email-account-recovery'
      fullPath: '/blog/temporary-email-account-recovery'
      preLoaderRoute: typeof BlogTemporaryEmailAccountRecoveryRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temp-email-tiktok-instagram-reddit': {
      id: '/blog/temp-email-tiktok-instagram-reddit'
      path: '/temp-email-tiktok-instagram-reddit'
      fullPath: '/blog/temp-email-tiktok-instagram-reddit'
      preLoaderRoute: typeof BlogTempEmailTiktokInstagramRedditRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/temp-email-chatgpt-claude-codex': {
      id: '/blog/temp-email-chatgpt-claude-codex'
      path: '/temp-email-chatgpt-claude-codex'
      fullPath: '/blog/temp-email-chatgpt-claude-codex'
      preLoaderRoute: typeof BlogTempEmailChatgptClaudeCodexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/platforms-blocking-temp-email-2026': {
      id: '/blog/platforms-blocking-temp-email-2026'
      path: '/platforms-blocking-temp-email-2026'
      fullPath: '/blog/platforms-blocking-temp-email-2026'
      preLoaderRoute: typeof BlogPlatformsBlockingTempEmail2026RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/is-temporary-email-safe-guide': {
      id: '/blog/is-temporary-email-safe-guide'
      path: '/is-temporary-email-safe-guide'
      fullPath: '/blog/is-temporary-email-safe-guide'
      preLoaderRoute: typeof BlogIsTemporaryEmailSafeGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/is-temporary-email-legal': {
      id: '/blog/is-temporary-email-legal'
      path: '/is-temporary-email-legal'
      fullPath: '/blog/is-temporary-email-legal'
      preLoaderRoute: typeof BlogIsTemporaryEmailLegalRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-to-use-temporary-email-for-testing-software': {
      id: '/blog/how-to-use-temporary-email-for-testing-software'
      path: '/how-to-use-temporary-email-for-testing-software'
      fullPath: '/blog/how-to-use-temporary-email-for-testing-software'
      preLoaderRoute: typeof BlogHowToUseTemporaryEmailForTestingSoftwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-to-use-anonymous-email-for-market-research': {
      id: '/blog/how-to-use-anonymous-email-for-market-research'
      path: '/how-to-use-anonymous-email-for-market-research'
      fullPath: '/blog/how-to-use-anonymous-email-for-market-research'
      preLoaderRoute: typeof BlogHowToUseAnonymousEmailForMarketResearchRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-to-create-temporary-email-guide': {
      id: '/blog/how-to-create-temporary-email-guide'
      path: '/how-to-create-temporary-email-guide'
      fullPath: '/blog/how-to-create-temporary-email-guide'
      preLoaderRoute: typeof BlogHowToCreateTemporaryEmailGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/email-privacy-for-small-businesses-guide': {
      id: '/blog/email-privacy-for-small-businesses-guide'
      path: '/email-privacy-for-small-businesses-guide'
      fullPath: '/blog/email-privacy-for-small-businesses-guide'
      preLoaderRoute: typeof BlogEmailPrivacyForSmallBusinessesGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-webinar-registration': {
      id: '/blog/disposable-email-webinar-registration'
      path: '/disposable-email-webinar-registration'
      fullPath: '/blog/disposable-email-webinar-registration'
      preLoaderRoute: typeof BlogDisposableEmailWebinarRegistrationRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-spam-protection-guide': {
      id: '/blog/disposable-email-spam-protection-guide'
      path: '/disposable-email-spam-protection-guide'
      fullPath: '/blog/disposable-email-spam-protection-guide'
      preLoaderRoute: typeof BlogDisposableEmailSpamProtectionGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-security-testing-guide': {
      id: '/blog/disposable-email-security-testing-guide'
      path: '/disposable-email-security-testing-guide'
      fullPath: '/blog/disposable-email-security-testing-guide'
      preLoaderRoute: typeof BlogDisposableEmailSecurityTestingGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-loyalty-programs': {
      id: '/blog/disposable-email-loyalty-programs'
      path: '/disposable-email-loyalty-programs'
      fullPath: '/blog/disposable-email-loyalty-programs'
      preLoaderRoute: typeof BlogDisposableEmailLoyaltyProgramsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-for-sweepstakes-guide': {
      id: '/blog/disposable-email-for-sweepstakes-guide'
      path: '/disposable-email-for-sweepstakes-guide'
      fullPath: '/blog/disposable-email-for-sweepstakes-guide'
      preLoaderRoute: typeof BlogDisposableEmailForSweepstakesGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-for-spam-protection-guide': {
      id: '/blog/disposable-email-for-spam-protection-guide'
      path: '/disposable-email-for-spam-protection-guide'
      fullPath: '/blog/disposable-email-for-spam-protection-guide'
      preLoaderRoute: typeof BlogDisposableEmailForSpamProtectionGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-for-freelancers': {
      id: '/blog/disposable-email-for-freelancers'
      path: '/disposable-email-for-freelancers'
      fullPath: '/blog/disposable-email-for-freelancers'
      preLoaderRoute: typeof BlogDisposableEmailForFreelancersRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-for-free-trials-guide': {
      id: '/blog/disposable-email-for-free-trials-guide'
      path: '/disposable-email-for-free-trials-guide'
      fullPath: '/blog/disposable-email-for-free-trials-guide'
      preLoaderRoute: typeof BlogDisposableEmailForFreeTrialsGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-for-coupon-codes': {
      id: '/blog/disposable-email-for-coupon-codes'
      path: '/disposable-email-for-coupon-codes'
      fullPath: '/blog/disposable-email-for-coupon-codes'
      preLoaderRoute: typeof BlogDisposableEmailForCouponCodesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/disposable-email-for-app-downloads': {
      id: '/blog/disposable-email-for-app-downloads'
      path: '/disposable-email-for-app-downloads'
      fullPath: '/blog/disposable-email-for-app-downloads'
      preLoaderRoute: typeof BlogDisposableEmailForAppDownloadsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/best-temporary-email-services-2026': {
      id: '/blog/best-temporary-email-services-2026'
      path: '/best-temporary-email-services-2026'
      fullPath: '/blog/best-temporary-email-services-2026'
      preLoaderRoute: typeof BlogBestTemporaryEmailServices2026RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/anonymous-email-survey-responses': {
      id: '/blog/anonymous-email-survey-responses'
      path: '/anonymous-email-survey-responses'
      fullPath: '/blog/anonymous-email-survey-responses'
      preLoaderRoute: typeof BlogAnonymousEmailSurveyResponsesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/anonymous-email-for-whistleblowers-guide': {
      id: '/blog/anonymous-email-for-whistleblowers-guide'
      path: '/anonymous-email-for-whistleblowers-guide'
      fullPath: '/blog/anonymous-email-for-whistleblowers-guide'
      preLoaderRoute: typeof BlogAnonymousEmailForWhistleblowersGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/anonymous-email-for-job-applications-guide': {
      id: '/blog/anonymous-email-for-job-applications-guide'
      path: '/anonymous-email-for-job-applications-guide'
      fullPath: '/blog/anonymous-email-for-job-applications-guide'
      preLoaderRoute: typeof BlogAnonymousEmailForJobApplicationsGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/anonymous-email-for-feedback-forms': {
      id: '/blog/anonymous-email-for-feedback-forms'
      path: '/anonymous-email-for-feedback-forms'
      fullPath: '/blog/anonymous-email-for-feedback-forms'
      preLoaderRoute: typeof BlogAnonymousEmailForFeedbackFormsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/anonymous-email-for-contact-forms': {
      id: '/blog/anonymous-email-for-contact-forms'
      path: '/anonymous-email-for-contact-forms'
      fullPath: '/blog/anonymous-email-for-contact-forms'
      preLoaderRoute: typeof BlogAnonymousEmailForContactFormsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/anonymous-email-customer-support-guide': {
      id: '/blog/anonymous-email-customer-support-guide'
      path: '/anonymous-email-customer-support-guide'
      fullPath: '/blog/anonymous-email-customer-support-guide'
      preLoaderRoute: typeof BlogAnonymousEmailCustomerSupportGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/6-billion-emails-leaked-2026': {
      id: '/blog/6-billion-emails-leaked-2026'
      path: '/6-billion-emails-leaked-2026'
      fullPath: '/blog/6-billion-emails-leaked-2026'
      preLoaderRoute: typeof Blog6BillionEmailsLeaked2026RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/12-percent-signups-use-temp-email': {
      id: '/blog/12-percent-signups-use-temp-email'
      path: '/12-percent-signups-use-temp-email'
      fullPath: '/blog/12-percent-signups-use-temp-email'
      preLoaderRoute: typeof Blog12PercentSignupsUseTempEmailRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  Blog12PercentSignupsUseTempEmailRoute: typeof Blog12PercentSignupsUseTempEmailRoute
  Blog6BillionEmailsLeaked2026Route: typeof Blog6BillionEmailsLeaked2026Route
  BlogAnonymousEmailCustomerSupportGuideRoute: typeof BlogAnonymousEmailCustomerSupportGuideRoute
  BlogAnonymousEmailForContactFormsRoute: typeof BlogAnonymousEmailForContactFormsRoute
  BlogAnonymousEmailForFeedbackFormsRoute: typeof BlogAnonymousEmailForFeedbackFormsRoute
  BlogAnonymousEmailForJobApplicationsGuideRoute: typeof BlogAnonymousEmailForJobApplicationsGuideRoute
  BlogAnonymousEmailForWhistleblowersGuideRoute: typeof BlogAnonymousEmailForWhistleblowersGuideRoute
  BlogAnonymousEmailSurveyResponsesRoute: typeof BlogAnonymousEmailSurveyResponsesRoute
  BlogBestTemporaryEmailServices2026Route: typeof BlogBestTemporaryEmailServices2026Route
  BlogDisposableEmailForAppDownloadsRoute: typeof BlogDisposableEmailForAppDownloadsRoute
  BlogDisposableEmailForCouponCodesRoute: typeof BlogDisposableEmailForCouponCodesRoute
  BlogDisposableEmailForFreeTrialsGuideRoute: typeof BlogDisposableEmailForFreeTrialsGuideRoute
  BlogDisposableEmailForFreelancersRoute: typeof BlogDisposableEmailForFreelancersRoute
  BlogDisposableEmailForSpamProtectionGuideRoute: typeof BlogDisposableEmailForSpamProtectionGuideRoute
  BlogDisposableEmailForSweepstakesGuideRoute: typeof BlogDisposableEmailForSweepstakesGuideRoute
  BlogDisposableEmailLoyaltyProgramsRoute: typeof BlogDisposableEmailLoyaltyProgramsRoute
  BlogDisposableEmailSecurityTestingGuideRoute: typeof BlogDisposableEmailSecurityTestingGuideRoute
  BlogDisposableEmailSpamProtectionGuideRoute: typeof BlogDisposableEmailSpamProtectionGuideRoute
  BlogDisposableEmailWebinarRegistrationRoute: typeof BlogDisposableEmailWebinarRegistrationRoute
  BlogEmailPrivacyForSmallBusinessesGuideRoute: typeof BlogEmailPrivacyForSmallBusinessesGuideRoute
  BlogHowToCreateTemporaryEmailGuideRoute: typeof BlogHowToCreateTemporaryEmailGuideRoute
  BlogHowToUseAnonymousEmailForMarketResearchRoute: typeof BlogHowToUseAnonymousEmailForMarketResearchRoute
  BlogHowToUseTemporaryEmailForTestingSoftwareRoute: typeof BlogHowToUseTemporaryEmailForTestingSoftwareRoute
  BlogIsTemporaryEmailLegalRoute: typeof BlogIsTemporaryEmailLegalRoute
  BlogIsTemporaryEmailSafeGuideRoute: typeof BlogIsTemporaryEmailSafeGuideRoute
  BlogPlatformsBlockingTempEmail2026Route: typeof BlogPlatformsBlockingTempEmail2026Route
  BlogTempEmailChatgptClaudeCodexRoute: typeof BlogTempEmailChatgptClaudeCodexRoute
  BlogTempEmailTiktokInstagramRedditRoute: typeof BlogTempEmailTiktokInstagramRedditRoute
  BlogTemporaryEmailAccountRecoveryRoute: typeof BlogTemporaryEmailAccountRecoveryRoute
  BlogTemporaryEmailDatingAppsPrivacyGuideRoute: typeof BlogTemporaryEmailDatingAppsPrivacyGuideRoute
  BlogTemporaryEmailEventRegistrationRoute: typeof BlogTemporaryEmailEventRegistrationRoute
  BlogTemporaryEmailForAffiliateProgramsRoute: typeof BlogTemporaryEmailForAffiliateProgramsRoute
  BlogTemporaryEmailForBetaTestingRoute: typeof BlogTemporaryEmailForBetaTestingRoute
  BlogTemporaryEmailForClassifiedAdsRoute: typeof BlogTemporaryEmailForClassifiedAdsRoute
  BlogTemporaryEmailForDevelopersGuideRoute: typeof BlogTemporaryEmailForDevelopersGuideRoute
  BlogTemporaryEmailForGamingPlatformsRoute: typeof BlogTemporaryEmailForGamingPlatformsRoute
  BlogTemporaryEmailForOnlinePrivacyRoute: typeof BlogTemporaryEmailForOnlinePrivacyRoute
  BlogTemporaryEmailForSigningUpRoute: typeof BlogTemporaryEmailForSigningUpRoute
  BlogTemporaryEmailForSocialMediaSignupRoute: typeof BlogTemporaryEmailForSocialMediaSignupRoute
  BlogTemporaryEmailForStudentsGuideRoute: typeof BlogTemporaryEmailForStudentsGuideRoute
  BlogTemporaryEmailForVerificationGuideRoute: typeof BlogTemporaryEmailForVerificationGuideRoute
  BlogTemporaryEmailForumRegistrationRoute: typeof BlogTemporaryEmailForumRegistrationRoute
  BlogTemporaryEmailLeadGenerationRoute: typeof BlogTemporaryEmailLeadGenerationRoute
  BlogTemporaryEmailMembershipSitesGuideRoute: typeof BlogTemporaryEmailMembershipSitesGuideRoute
  BlogTemporaryEmailOnlinePrivacyGuideRoute: typeof BlogTemporaryEmailOnlinePrivacyGuideRoute
  BlogTemporaryEmailPrivacyProtectionGuideRoute: typeof BlogTemporaryEmailPrivacyProtectionGuideRoute
  BlogTemporaryEmailSaasSignupGuideRoute: typeof BlogTemporaryEmailSaasSignupGuideRoute
  BlogTemporaryEmailSoftwareTrialsRoute: typeof BlogTemporaryEmailSoftwareTrialsRoute
  BlogTemporaryEmailVsPermanentEmailDifferencesRoute: typeof BlogTemporaryEmailVsPermanentEmailDifferencesRoute
  BlogUsingDisposableEmailForNewsletterSignupRoute: typeof BlogUsingDisposableEmailForNewsletterSignupRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  Blog12PercentSignupsUseTempEmailRoute: Blog12PercentSignupsUseTempEmailRoute,
  Blog6BillionEmailsLeaked2026Route: Blog6BillionEmailsLeaked2026Route,
  BlogAnonymousEmailCustomerSupportGuideRoute:
    BlogAnonymousEmailCustomerSupportGuideRoute,
  BlogAnonymousEmailForContactFormsRoute:
    BlogAnonymousEmailForContactFormsRoute,
  BlogAnonymousEmailForFeedbackFormsRoute:
    BlogAnonymousEmailForFeedbackFormsRoute,
  BlogAnonymousEmailForJobApplicationsGuideRoute:
    BlogAnonymousEmailForJobApplicationsGuideRoute,
  BlogAnonymousEmailForWhistleblowersGuideRoute:
    BlogAnonymousEmailForWhistleblowersGuideRoute,
  BlogAnonymousEmailSurveyResponsesRoute:
    BlogAnonymousEmailSurveyResponsesRoute,
  BlogBestTemporaryEmailServices2026Route:
    BlogBestTemporaryEmailServices2026Route,
  BlogDisposableEmailForAppDownloadsRoute:
    BlogDisposableEmailForAppDownloadsRoute,
  BlogDisposableEmailForCouponCodesRoute:
    BlogDisposableEmailForCouponCodesRoute,
  BlogDisposableEmailForFreeTrialsGuideRoute:
    BlogDisposableEmailForFreeTrialsGuideRoute,
  BlogDisposableEmailForFreelancersRoute:
    BlogDisposableEmailForFreelancersRoute,
  BlogDisposableEmailForSpamProtectionGuideRoute:
    BlogDisposableEmailForSpamProtectionGuideRoute,
  BlogDisposableEmailForSweepstakesGuideRoute:
    BlogDisposableEmailForSweepstakesGuideRoute,
  BlogDisposableEmailLoyaltyProgramsRoute:
    BlogDisposableEmailLoyaltyProgramsRoute,
  BlogDisposableEmailSecurityTestingGuideRoute:
    BlogDisposableEmailSecurityTestingGuideRoute,
  BlogDisposableEmailSpamProtectionGuideRoute:
    BlogDisposableEmailSpamProtectionGuideRoute,
  BlogDisposableEmailWebinarRegistrationRoute:
    BlogDisposableEmailWebinarRegistrationRoute,
  BlogEmailPrivacyForSmallBusinessesGuideRoute:
    BlogEmailPrivacyForSmallBusinessesGuideRoute,
  BlogHowToCreateTemporaryEmailGuideRoute:
    BlogHowToCreateTemporaryEmailGuideRoute,
  BlogHowToUseAnonymousEmailForMarketResearchRoute:
    BlogHowToUseAnonymousEmailForMarketResearchRoute,
  BlogHowToUseTemporaryEmailForTestingSoftwareRoute:
    BlogHowToUseTemporaryEmailForTestingSoftwareRoute,
  BlogIsTemporaryEmailLegalRoute: BlogIsTemporaryEmailLegalRoute,
  BlogIsTemporaryEmailSafeGuideRoute: BlogIsTemporaryEmailSafeGuideRoute,
  BlogPlatformsBlockingTempEmail2026Route:
    BlogPlatformsBlockingTempEmail2026Route,
  BlogTempEmailChatgptClaudeCodexRoute: BlogTempEmailChatgptClaudeCodexRoute,
  BlogTempEmailTiktokInstagramRedditRoute:
    BlogTempEmailTiktokInstagramRedditRoute,
  BlogTemporaryEmailAccountRecoveryRoute:
    BlogTemporaryEmailAccountRecoveryRoute,
  BlogTemporaryEmailDatingAppsPrivacyGuideRoute:
    BlogTemporaryEmailDatingAppsPrivacyGuideRoute,
  BlogTemporaryEmailEventRegistrationRoute:
    BlogTemporaryEmailEventRegistrationRoute,
  BlogTemporaryEmailForAffiliateProgramsRoute:
    BlogTemporaryEmailForAffiliateProgramsRoute,
  BlogTemporaryEmailForBetaTestingRoute: BlogTemporaryEmailForBetaTestingRoute,
  BlogTemporaryEmailForClassifiedAdsRoute:
    BlogTemporaryEmailForClassifiedAdsRoute,
  BlogTemporaryEmailForDevelopersGuideRoute:
    BlogTemporaryEmailForDevelopersGuideRoute,
  BlogTemporaryEmailForGamingPlatformsRoute:
    BlogTemporaryEmailForGamingPlatformsRoute,
  BlogTemporaryEmailForOnlinePrivacyRoute:
    BlogTemporaryEmailForOnlinePrivacyRoute,
  BlogTemporaryEmailForSigningUpRoute: BlogTemporaryEmailForSigningUpRoute,
  BlogTemporaryEmailForSocialMediaSignupRoute:
    BlogTemporaryEmailForSocialMediaSignupRoute,
  BlogTemporaryEmailForStudentsGuideRoute:
    BlogTemporaryEmailForStudentsGuideRoute,
  BlogTemporaryEmailForVerificationGuideRoute:
    BlogTemporaryEmailForVerificationGuideRoute,
  BlogTemporaryEmailForumRegistrationRoute:
    BlogTemporaryEmailForumRegistrationRoute,
  BlogTemporaryEmailLeadGenerationRoute: BlogTemporaryEmailLeadGenerationRoute,
  BlogTemporaryEmailMembershipSitesGuideRoute:
    BlogTemporaryEmailMembershipSitesGuideRoute,
  BlogTemporaryEmailOnlinePrivacyGuideRoute:
    BlogTemporaryEmailOnlinePrivacyGuideRoute,
  BlogTemporaryEmailPrivacyProtectionGuideRoute:
    BlogTemporaryEmailPrivacyProtectionGuideRoute,
  BlogTemporaryEmailSaasSignupGuideRoute:
    BlogTemporaryEmailSaasSignupGuideRoute,
  BlogTemporaryEmailSoftwareTrialsRoute: BlogTemporaryEmailSoftwareTrialsRoute,
  BlogTemporaryEmailVsPermanentEmailDifferencesRoute:
    BlogTemporaryEmailVsPermanentEmailDifferencesRoute,
  BlogUsingDisposableEmailForNewsletterSignupRoute:
    BlogUsingDisposableEmailForNewsletterSignupRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  BlogRoute: BlogRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
